services:
  app:
    build: .
    container_name: mask_rcnn_durian_locule_counting_test
    command: /bin/bash -c "jupyter notebook --ip=0.0.0.0 --port=9999 --no-browser --allow-root"
    ports:
      - "9999:9999"
      - "6006:6006"
    volumes:
      - .:/app
    stdin_open: true # -i
    tty: true # -t
    ipc: host # --ipc=host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu] # --gpus all
